# Generated by Django 6.0.2 on 2026-02-18 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del autor', max_length=100)),
                ('email', models.EmailField(help_text='Correo electrónico único', max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre único de la categoría', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del post', max_length=200)),
                ('content', models.TextField(help_text='Contenido del post')),
                ('published_date', models.DateTimeField(auto_now_add=True, help_text='Fecha de publicación')),
                ('author', models.ForeignKey(help_text='Autor del post', on_delete=django.db.models.deletion.CASCADE, to='blog.author')),
                ('category', models.ForeignKey(help_text='Categoría del post', on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
        ),
    ]
