# Generated by Django 6.0.2 on 2026-02-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen opcional del post', null=True, upload_to='posts/'),
        ),
    ]
